### ISSUE TITLE
get 과 post는 어떠한 URL측면에서 어떠한 차이가 있을까요?

### ISSUE THREAD

**Issue by Seobway23** [ppobbi-study/CS_Study_Hub#107]

**Comment by Seobway23** [comment]
URL 자체는 리소스를 식별하는 데 사용됩니다.

하지만, CRUD 작업에 따라 HTTP 메소드를 통해 결정됩니다.

- 생성의 경우 POST method
- 읽기의 경우 GET method ( 쿼리 스트링을 사용해  URL + & 추가& 추가)
- 업데이트의 경우 PUT(전체) or PATCH(부분) method
- 삭제의 경우 DELETE method
가 있습니다.

**Comment by kimmainsain** [comment]
<h3>답변</h3>

* url에 저장되어있는 자원을 HTTP method(POST GET PUT DELETE)를 활용해서 접근하기에, url은 변하지 않습니다.
* URL : 웹 상에서 자원의 위치를 나타내기 위한 uri의 한 형태
* URI : 인터넷에서 자원을 식별하는 데 사용되는 표준화된 문자열이며, URL URN을 포괄하는 넓은 개념

**Comment by freakFlow** [comment]
### 답변
REST API는 HTTP 메소드를 통해서 자원에 대한 행동을 결정하기 때문에 크게 바뀌지는 않습니다.
